### ISSUE TITLE
Font colour for the SA button

### ISSUE THREAD

**Issue by marinaado** [TheIdentitySelector/thiss-js#117]
In addition to configuration parameter to change the colour of the button and the background bellow the button, a configuration parameter for font colour for text presented on and bellow the button should also exist for full customisation ability. The instructions at https://thiss-js.readthedocs.io/en/latest/components.html and at https://seamlessaccess.atlassian.net/wiki/spaces/DOCUMENTAT/pages/458783/States+Styles+and+Assets should be updated accordingly. 

Thanks!

**Comment by leifj** [comment]
fixed
