### ISSUE TITLE
node-gyp version 3.8.0 requires python 2.x

### ISSUE THREAD

**Issue by skoranda** [TheIdentitySelector/thiss-js#119]
The file package-lock.json sets the node-gyp version to 3.8.0, but that is an old version of gyp that still requires python 2.x.

**Comment by leifj** [comment]
This is due to https://github.com/sass/node-sass/issues/2877 - looks like the solution is to switch to dart-sass. What do you think @HotEmu ?

**Comment by HotEmu** [comment]
If node-sass is causing problems because of its dependencies then let's switch it up.

**Comment by enriquepablo** [comment]
obsolete
