### ISSUE TITLE
Increase target size of "delete" institution

### ISSUE THREAD

**Issue by Bojhan** [TheIdentitySelector/thiss-js#264]
The delete button is currently to small to meet WCAG 2.2 criteria on target sizes.

We would like to have a invisible div around it, which enlarges the target size to at least 60 high and 40 wide. If possible this should also show the word "delete" below the cross when hovered/focused. This to give a indicator other than color on selecting the delete action.

<img width="553" alt="Screenshot 2024-01-12 at 10 14 58" src="https://github.com/TheIdentitySelector/thiss-ds-js/assets/209807/89e7940c-5b1b-4820-88ca-ede4bf3423d8">

**Comment by Bojhan** [comment]
We should also update the "Done" styling

**Comment by enriquepablo** [comment]
Done in version 2.0.1
