### ISSUE TITLE
Indicate unable to verify returning site

### ISSUE THREAD

**Issue by Bojhan** [TheIdentitySelector/thiss-js#270]
Seamless access in some cases will not know if users are send back to an "approved" URL. 

SP's are requested to publish the allowed URLs a discovery service can send responses back to, however they are not required to do so - and thus it happens that we cannot verify. Given that this poses a security risk, we need to signal this to users.

We see three scenario's:

1. DiscoveryResponse info and the return URL is among them; UI should indicate that all is good;
2. DiscoveryResponse info and the return URL is not among them; UI should indicate that not all is good
3. DiscoveryResponse info and the return URL is not among them; UI should indicate that user should check themselves.

Given that we should not indicate that all is good, 1) is covered by our current flow.

For scenario 2/3 we will send the same message, the fact that we cannot identify return path from the origin. 

The Continue button will send them back to the previous interaction/page.

![Unkown return](https://github.com/TheIdentitySelector/thiss-js/assets/209807/ee6103b7-7f6a-41e7-9d9b-5baa400abc4c)
![Unkown return_ Different domain](https://github.com/TheIdentitySelector/thiss-js/assets/209807/c597903c-7373-43e4-a8ed-5474b9687efb)

**Comment by Bojhan** [comment]
Final comments here:
- the wording "access path" will be subject to some user-testing from my side.
- the link will go to a page on SA documentation
- Continue goes back to the previous page.

**Comment by Bojhan** [comment]
@enriquepablo For back can you implement the two possible scenario's:
- Go back to Search
- Go back to Edit institutions

**Comment by enriquepablo** [comment]
Done in version 2.0.1
