### ISSUE TITLE
Builds are failing because NodeJS are out of sync.

### ISSUE THREAD

**Issue by HotEmu** [TheIdentitySelector/thiss-js#37]
Replicate Bug: change any line of code in any of the files and create a new PR.

Problem: any build will fail during the SASS compilation phase. Package "node-sass" has to be rebuilt per the following error:

Error: Missing binding /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
Found bindings for the following environments:
- Linux 64-bit with Node.js 8.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.

Solution: force node-sass rebuild

**Comment by leifj** [comment]
PR #38 fixes this I guess...
