### ISSUE TITLE
Google Fonts Webpack Plugin does not handle errors.

### ISSUE THREAD

**Issue by HotEmu** [TheIdentitySelector/thiss-js#40]
Issue: If the Webpack plugin does not get "200" response status from Google Font server, its Promise does not handle an error, resulting in a build that needs to be restarted. In the attached screenshot we are taken to a "download" function in the NPM package that does not handle errors well.

Fix: Potential fixes: get rid of the plugin, fix the plugin.

<img width="1440" alt="Screen Shot 2020-04-10 at 1 39 53 PM" src="https://user-images.githubusercontent.com/8418787/79025220-ba342f80-7b4a-11ea-97a2-3c3a7c77f2ba.png">

**Comment by leifj** [comment]
fixed by #41
