### ISSUE TITLE
show version https://service.seamlessaccess.org/thiss.js

### ISSUE THREAD

**Issue by mariahaider** [TheIdentitySelector/thiss-js#56]
@leifj can you please include the thiss-js version in the URL, https://service.seamlessaccess.org/thiss.js?

**Comment by leifj** [comment]
From 1.3.0 there is a /metadata.json that contains version info.

**Comment by leifj** [comment]
wget -qO- https://service.seamlessaccess.org/manifest.json | jq .version -
